# Generated by Django 5.1.1 on 2024-09-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('performance', 'row', 'seat')},
        ),
    ]
