# Generated by Django 5.1.1 on 2024-09-20 10:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.poster_image_file_path),
        ),
    ]
